### ISSUE TITLE
Enhance the task list ui

### ISSUE THREAD

**Issue by TBladen** [TBladen/Tasked#2]
The task list ui should show the following items for each task:
- [x]  name
- [x] expiry date
- [x]  completion indicator
- [x]  warning if imminent expiry

Searching/filtering and ordering should be added to the task list screen.
Suggested filter options:
- [ ]  group
- [ ]  expiry time (within a range)
- [ ]  name (string pattern matching?)
- [ ]  number of children

Other features (possibly not for first release):
- [ ]  swipe left to delete (may interfere with tab changing)
- [ ]  long press + select to batch delete
- [ ]  context menu to manipulate tasks
